# Generated by Django 4.1 on 2024-05-27 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medidores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('idAlerta', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('fechaAlta', models.DateTimeField()),
                ('medidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medidores.medidores')),
            ],
        ),
    ]
